import { Holiday } from "../types/holidays";

const mockHolidays: Holiday[] = [
  {
    id: "1",
    name: "New Year's Day",
    date: "2023-01-01",
    day: "Sunday",
    type: "Public",
    location: "New York",
  },
  {
    id: "2",
    name: "Martin Luther King, Jr. Day",
    date: "2023-01-16",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "3",
    name: "Valentine's Day",
    date: "2023-02-14",
    day: "Tuesday",
    type: "Optional",
    location: "All",
  },
  {
    id: "4",
    name: "Presidents' Day",
    date: "2023-02-20",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "5",
    name: "Holi",
    date: "2023-03-08",
    day: "Wednesday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "6",
    name: "Good Friday",
    date: "2023-04-07",
    day: "Friday",
    type: "Public",
    location: "London",
  },
  {
    id: "7",
    name: "Memorial Day",
    date: "2023-05-29",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "8",
    name: "Eid al-Fitr",
    date: "2023-04-21",
    day: "Friday",
    type: "Optional",
    location: "All",
  },
  {
    id: "9",
    name: "Independence Day",
    date: "2023-07-04",
    day: "Tuesday",
    type: "Public",
    location: "New York",
  },
  {
    id: "10",
    name: "Raksha Bandhan",
    date: "2023-08-30",
    day: "Wednesday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "11",
    name: "Labor Day",
    date: "2023-09-04",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "12",
    name: "Diwali",
    date: "2023-11-12",
    day: "Sunday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "13",
    name: "Thanksgiving Day",
    date: "2023-11-23",
    day: "Thursday",
    type: "Public",
    location: "New York",
  },
  {
    id: "14",
    name: "Christmas Day",
    date: "2023-12-25",
    day: "Monday",
    type: "Public",
    location: "All",
  },
  {
    id: "15",
    name: "New Year's Day",
    date: "2024-01-01",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "16",
    name: "Republic Day (India)",
    date: "2024-01-26",
    day: "Friday",
    type: "Public",
    location: "Bangalore",
  },
  {
    id: "17",
    name: "Easter Monday",
    date: "2024-04-01",
    day: "Monday",
    type: "Optional",
    location: "London",
  },
  {
    id: "18",
    name: "Eid al-Adha",
    date: "2024-06-16",
    day: "Sunday",
    type: "Optional",
    location: "All",
  },
  {
    id: "19",
    name: "Independence Day (USA)",
    date: "2024-07-04",
    day: "Thursday",
    type: "Public",
    location: "New York",
  },
  {
    id: "20",
    name: "Christmas Day",
    date: "2024-12-25",
    day: "Wednesday",
    type: "Public",
    location: "All",
  },
  {
    id: "21",
    name: "New Year's Day",
    date: "2025-01-01",
    day: "Wednesday",
    type: "Public",
    location: "New York",
  },
  {
    id: "22",
    name: "Martin Luther King, Jr. Day",
    date: "2025-01-20",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "23",
    name: "Valentine's Day",
    date: "2025-02-14",
    day: "Friday",
    type: "Optional",
    location: "All",
  },
  {
    id: "24",
    name: "Presidents' Day",
    date: "2025-02-17",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "25",
    name: "Holi",
    date: "2025-03-14",
    day: "Friday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "26",
    name: "Good Friday",
    date: "2025-04-18",
    day: "Friday",
    type: "Public",
    location: "London",
  },
  {
    id: "27",
    name: "Memorial Day",
    date: "2025-05-26",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "28",
    name: "Eid al-Fitr",
    date: "2025-03-31",
    day: "Monday",
    type: "Optional",
    location: "All",
  },
  {
    id: "29",
    name: "Independence Day",
    date: "2025-07-04",
    day: "Friday",
    type: "Public",
    location: "New York",
  },
  {
    id: "30",
    name: "Raksha Bandhan",
    date: "2025-08-09",
    day: "Saturday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "31",
    name: "Labor Day",
    date: "2025-09-01",
    day: "Monday",
    type: "Public",
    location: "New York",
  },
  {
    id: "32",
    name: "Diwali",
    date: "2025-10-21",
    day: "Tuesday",
    type: "Optional",
    location: "Bangalore",
  },
  {
    id: "33",
    name: "Thanksgiving Day",
    date: "2025-11-27",
    day: "Thursday",
    type: "Public",
    location: "New York",
  },
  {
    id: "34",
    name: "Christmas Day",
    date: "2025-12-25",
    day: "Thursday",
    type: "Public",
    location: "All",
  },
];

export const fetchHolidays = async (year: string, location: string): Promise<Holiday[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      let holidaysToReturn = mockHolidays.filter(holiday => holiday.date.startsWith(year));

      if (location !== "All") {
        holidaysToReturn = holidaysToReturn.filter(holiday => holiday.location === location);
      }
      resolve(holidaysToReturn);
    }, 500); // Simulate network delay
  });
};
