// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxfpisxuyjkrwbqhmtvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZnBpc3h1eWprcndicWhtdHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDA3MzUsImV4cCI6MjA3Mjk3NjczNX0.PSkLZP4AyQgY7JNbIgj2Ng8cSFh_4gTR-_yVmlow4mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});